### ISSUE TITLE
功能详情询问

### ISSUE THREAD

**Issue by CAESIUS-TIM** [Littlefean/SmartPython#1]
https://github.com/Littlefean/SmartPython/blob/4a361dc2424898eb5907fcaeb9bb644017180f79/python%E8%BF%B7%E6%83%91%E8%A1%8C%E4%B8%BA/%E6%88%91%E8%A6%81%E6%88%91%E8%87%AA%E5%B7%B1/main.py#L26

请问这个是想实现什么功能，比如：

```python
a.val = list(range(100))
print(a[0, 1, (2, 5)])  # [0, 1, [2, 5]]
print(a[0, "abc"])  # raise ValueError

a.val = [[i] * 2 for i in range(10)]
print(a[0, [1, [2, 3]]])  # [[0, 0], [[1, 1], [[2, 2], [3, 3]]]]
```

**Comment by Littlefean** [comment]
这个“我要我自己”当时只是想看看中括号里面都可以怎么写，为什么能随便写，本来是想做成迷惑行为系列的，也没想具体实现什么功能。
https://www.bilibili.com/video/BV1ar4y1V7kL

**Comment by CAESIUS-TIM** [comment]
👌🏻，thx！不过提一下建议，pep8推荐使用`isinstance`而不是`type`判断类型，看着有点别扭😂。

**Comment by zty012** [comment]
> 👌🏻，thx！不过提一下建议，pep8推荐使用`isinstance`而不是`type`判断类型，看着有点别扭😂。

#3
